### ISSUE TITLE
Shell choice config implementation

### ISSUE THREAD

**Issue by halfbrained** [halfbrained/cuda_terminal_plus#10]
Previous version of Terminal plugin had three config properties for shell choice: Linux, Windows, Mac.
Should it be replaced by one general pair: `path` and `arguments`, or expand previous version to three such pairs (`linux_shell` + `linux_shell_arguments`, ...)?

@Alexey-T

**Comment by Alexey-T** [comment]
Better 3 pairs.
to allow users to have 'ksh' or 'zsh'.

(windows_path, windows_args),
(linux_.....)
(macos_....)

**Comment by Alexey-T** [comment]
because 'path' is without space, we can have option like 2 in 1
windows_cmd=cmd /some /args /here
linux_cmd=/usr/bin/ksh /some /args

**Comment by halfbrained** [comment]
Got it
