### ISSUE TITLE
collapse /home/name/paths via ~

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_terminal_plus#12]
- In sidebar button hint
- In terminal statusbar cells hint
- In history file

**Comment by halfbrained** [comment]
First two - sure, but modifying the commands seems like a terrible idea.
checked, bash saves literally, from history file:  

    cd ~
    cd /home/user

**Comment by Alexey-T** [comment]
yes, no need in command history, but needed in 'states of plugin' file, in "filename" val.

**Comment by Alexey-T** [comment]
ie needed in cuda_terminal_plus_state.json

**Comment by halfbrained** [comment]
fixed (https://github.com/halfbrained/cuda_terminal_plus/commit/05ad8c70ac68d63ead27afb9fe6dc42326995510)
