### ISSUE TITLE
use lazy events?

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_terminal_plus#20]
```
[item1]
section=events
events=on_exit,on_tab_change,on_tab_move,on_snippet
```

```
Python 3.8
Init: cuda_console_complete
Init: cuda_terminal_plus
Loaded session: "history session.json", 20ms, 0 file(s)
Startup: 210ms, plugins: 30ms (console_complete 15ms, terminal_plus 21ms)
```
this makes plugin start if Cud opens some tabs from session.
maybe lazy events?
so plugin won't start with Cud session?
https://wiki.freepascal.org/CudaText_API#Lazy_events

**Comment by halfbrained** [comment]
Thanks, that makes sense :) changed (929731c1e9e247b29941cae9187bf5bc75e08994)
