### ISSUE TITLE
cmd 'toggle focus: editor - its terminal'

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_terminal_plus#22]
I closed the file attached to terminal.
terminal is opened.
now I call SUBJ and I want that Cud opens _that file_ (which I closed).

**Comment by halfbrained** [comment]
Currently this command, when focus is not in editor or terminal, brings focus to the active editor tab; probably should be editor of the active terminal if any, right?

**Comment by Alexey-T** [comment]
> when focus is not in editor or terminal, brings focus to the active editor tab;

**Comment by Alexey-T** [comment]
> when focus is not in editor or terminal, brings focus to the active editor tab;

it is OK.
if IF focused the T's input or T's memo area, better to open file attached for them (if file attached)

**Comment by halfbrained** [comment]
Ok, will leave as is:

* in term - go to its file
* in file - go to its term
* anywhere else - just go to current editor tab

**Comment by halfbrained** [comment]
fixed here de269976d6a25f80881fbee0adbf376c4d25e8d5

**Comment by Alexey-T** [comment]
now OK
