### ISSUE TITLE
cmd 'toggle focus: ed - terminal'

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_terminal_plus#24]
it don't activate Terminal panel if Console panel is active.

**Comment by halfbrained** [comment]
You mean when focus not in editor and not in terminal, besides focusing current editor, it should also show its terminal?
(currently in this situation it will focus editor on the first invocation, and then its terminal on the next)

**Comment by Alexey-T** [comment]
no, if focus in editor (it has term!) and Cud Console is opened, 'toggle' must chg Console to Term

**Comment by Alexey-T** [comment]
ah, it's OK.
but.
if Term is not started yet, and I call "toggle" from editor, term is opened w/o focusing input!

**Comment by halfbrained** [comment]
fixed (cdab2e4ba88136aa79a6fb168b2103e49c650f44)
