### ISSUE TITLE
terminal for untitled tabs?

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_terminal_plus#25]
not sure what to do if I press + for untitled tab active.
disable adding?
or enable?
if enable- pls show statusbar hint "Terminal+: untitled4" ('untitled4' from PROP_TAB_TITLE)

let's disable it?

what to do if I do 'save file as' to different filename? how plugin mapping will change.

**Comment by halfbrained** [comment]
'+' for untitled tabs is currently equivalent to command 'Add terminal for user home directory' (creates a terminal with no  file attached), and working directory will be either project main file's or user home directory depending on 'start_dir' config option.

> what to do if I do 'save file as' to different filename? how plugin mapping will change.

If I choose to remap on save, then it will probably have to remap all terminals for that file... and that doesn't seem completely safe.
Is adding a 'Remap terminal to current file' (with a dialog to ask if `.cwd` should change) is a reasonable reasonable solution?

**Comment by Alexey-T** [comment]
new command? please no. 
'save as' support is not much needed.

**Comment by halfbrained** [comment]
ok :)

**Comment by halfbrained** [comment]
> let's disable it?

Oh, you mean disable the button...
Maybe just (add and) change the hint? 
'Add terminal (for current file)' on normal tab, and 'Add terminal for user home directory' for untitled?
And maybe change an icon to a clear version for untitled, so it was obvious?

**Comment by Alexey-T** [comment]
2 hints? one universal hint is ok: "Add terminal (attached to file, for named documents)"
