### ISSUE TITLE
btn '+' adds terminal not at the end of statusbar

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_terminal_plus#27]
yellow was opened.
now I press `+` 4 times: new items added BEFORE yellow item.
bug?

![Screenshot from 2021-02-16 11-24-43](https://user-images.githubusercontent.com/4154978/108036785-b9f9a000-7049-11eb-9b00-8203e2ae96dc.png)

**Comment by Alexey-T** [comment]
@jairomartinezA @kvichans @dinkumoil @tmsg-gh @olehl @iramsoft - welcome to alpha testing of Terminal+

**Comment by halfbrained** [comment]
Not a bug, terminals are sorted: 

1. without a file 
2. with editor tabs opened (these are sorted in order of their editor tabs)
3. last are terminals with files without an editor tab (closed files).

CudaText does not support drag and drop for a simple way to reorder terminals, so I force this sorting.

I am open to suggestions on this matter :)

**Comment by Alexey-T** [comment]
Ok
