### ISSUE TITLE
can we use editor's font for input-field? now it's different

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_terminal_plus#28]
![Screenshot from 2021-02-16 11-29-35](https://user-images.githubusercontent.com/4154978/108037216-515ef300-704a-11eb-9bfb-fcefc8aed701.png)

**Comment by halfbrained** [comment]
fixed (4fd9f743ecf4ab21662272c442ea45cf9b2ec662)
But it was not my doing. A CudaText bug perhaps?

**Comment by Alexey-T** [comment]
hm, maybe..
