### ISSUE TITLE
fix readme.txt, TODO for Alexey

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_terminal_plus#30]
- write all command names from install.inf - like in .inf
- describe 'toggle' command in details

**Comment by Alexey-T** [comment]
[readme.txt](https://github.com/halfbrained/cuda_terminal_plus/files/5989222/readme.txt)

pls use this.

**Comment by halfbrained** [comment]
Thank you, done (53b7a45cefa360f43ae3e30c616e4c00062c9e99)
