### ISSUE TITLE
Give a visual cue to a terminal without a file?

### ISSUE THREAD

**Issue by halfbrained** [halfbrained/cuda_terminal_plus#36]
Currently terminals without a file are just sorted before others. Maybe also give them a different font color, or add an asterisk or something to the name?

@Alexey-T

**Comment by Alexey-T** [comment]
yes, it would be nice.

**Comment by Alexey-T** [comment]
"~" as a cell caption?

**Comment by halfbrained** [comment]
maybe '^'? since '~' means home dir?

**Comment by Alexey-T** [comment]
OK

**Comment by Alexey-T** [comment]
solved, tks.
