### ISSUE TITLE
add option 'panel_layout'

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_terminal_plus#4]
input box + break-button: in panel-one.
statusbar - in panel-two.
place panel-one + panel-two on same parent panel (on dialog).

option must change layout of these panels:

- statusbar on the right, input on the rest space

or 

- statusbar on the top, input on the bottom

**Comment by halfbrained** [comment]
Separate panels should be the default? Looks cleaner

**Comment by Alexey-T** [comment]
Ok,default.
