### ISSUE TITLE
hint for "+" button

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_terminal_plus#40]
for + button I see hint 
`Add terminal (attached to file, for named documents)`
even if I have focused UNTITLED document.
and + button adds free terminal if i press it.
so hint is not OK?
it's universal hint for names+unnamed tabs? then change it to 
`Add terminal (it will be "free" terminal for untitled document)`

**Comment by halfbrained** [comment]
Stopped at 'Add terminal for current document (will be ^free for Untitled)'

**Comment by Alexey-T** [comment]
Ок
