### ISSUE TITLE
reopen Cud-- one terminal is opened always?

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_terminal_plus#42]
this work
![Screenshot from 2021-02-17 12-53-22](https://user-images.githubusercontent.com/4154978/108187129-301c0680-711f-11eb-9e2f-81972782e4bb.png)

I press X, closed all.
restarted Cud.
called 'Open'.===> free terminal is still here!

**Comment by Alexey-T** [comment]
after X press
cuda_terminal_plus_state.json
```
[
  {
    "filepath": "",
    "name": "",
    "cwd": "~",
    "lastactive": 1613555724.072948,
    "icon": "",
    "history": []
  }
]
```

**Comment by halfbrained** [comment]
That is supposed to be a feature :) 

Is it not expected to have a terminal when you open a terminal plugin?

**Comment by Alexey-T** [comment]
OK
