### ISSUE TITLE
cmd 'Open': if possible, put focus to terminal for the current editor

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_terminal_plus#44]
from this
![Screenshot from 2021-02-17 15-41-31](https://user-images.githubusercontent.com/4154978/108205930-c14aa780-7136-11eb-83c2-8984102ba688.png)

i call 'open' and get this - terminal for current file user.json is passive, 1st 'free term' is acttive!
![Screenshot from 2021-02-17 15-41-35](https://user-images.githubusercontent.com/4154978/108205981-d45d7780-7136-11eb-8e50-d81d8ff5f8b8.png)

**Comment by halfbrained** [comment]
Isn't this a job for the 'toggle' command?

* Toggle - go to current file's terminal
* Open - go to where you left off

**Comment by Alexey-T** [comment]
hmm, OK.
