### ISSUE TITLE
VSCode can scroll "git diff" output by arrows up/down, close by Q

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_terminal_plus#46]
I am not sure we can do this too, can we?

**Comment by halfbrained** [comment]
Not designed for this.

At the moment the next best thing though is replacing

    self._open_terminal()

with

    self._open_terminal(columns=80, lines=MAX_BUFFER//80)

~~will tell `git diff` (and others) to fill terminal's buffer with its output. (Not sure if this is enough, maybe people are frequently reading diffs that a larger than the default 100k buffer in a terminal :) )~~

My mistake, that will not be a limit of MAX_BUFFER bytes, but a number of lines - 1250 lines for the default 100k buffer.

If this is not enough, it might be possible to make a sort of flexible buffer (instead of hard limit with MAX_BUFFER), that will at least hold an output of one command even if it is larger than MAX_BUFFER.

**Comment by Alexey-T** [comment]
Ok, so we cannot scroll 'git diff' result.

**Comment by halfbrained** [comment]
Nope. (At least not a nice way. Scrolling down probably can be done, but not up.)

**Comment by Alexey-T** [comment]
we cannot handle Down-arrow, and if terminal output ends with line
```
:
```
we send Down key to app?

**Comment by halfbrained** [comment]
One problem is that we are just reading the bytes output of terminal, so when I scroll back - lines that should appear at the top - appear at the bottom:

![term_scroll_up](https://user-images.githubusercontent.com/74829192/108625577-55c54a80-7454-11eb-9199-aee41d91af17.png)

And another problem - I cant figure out how to send `Up` and `Down` to terminal. According to the wiki on ANSI escape codes  `b'\x1b\x9bA'` is a "Cursor Up" code, but it doesn't seem to work for me...

**Comment by halfbrained** [comment]
Looked through the terminal data, and I can see how it does the "scroll back" thing. So I might be able to make it work, will investigate this further a bit later.

**Comment by Alexey-T** [comment]
>One problem is that we are just reading the bytes output of terminal, so when I scroll back - lines that should appear at the top - appear at the bottom:

so I ask only for scroll-down by arrow-down, w/o scrolling up.

**Comment by halfbrained** [comment]
Oh... well in that case I will just investigate sending the down key. (But sending 'e' (`less`'s hotkey) already works, so there is a fallback)

**Comment by Alexey-T** [comment]
That is good to hear..

**Comment by halfbrained** [comment]
Well this is peculiar, sending arrow keys to terminal works (`b'\x1b[A'` and `b'\x1b[B'`), but not in `git diff` output...

**Comment by Alexey-T** [comment]
can we make some hack for `git <anything>` command, so it runs w/o interactive scroll?

**Comment by halfbrained** [comment]
That is easy, but the `git <anything>` output might not fit in the buffer (MAX_BUFFER plugin option), then the head part of the output will be cut off in the memo.

I spent some time on this and couldn't find a way to use arrow keys... so this might be the best option at the moment

> we cannot handle Down-arrow, and if terminal output ends with line
> 
> ```
> :
> ```
> 
> we send Down key to app?

**Comment by halfbrained** [comment]
Ok, I figured out how to send arrow keys and others...

If just scrolling further is enough, I can just send to terminal `Down` to scroll further (and `Page Down` probably should be added) when memo is at the bottom. `Down` does nothing in `bash`, but scrolls further in `less`. Good?

**Comment by Alexey-T** [comment]
yes, good.

**Comment by halfbrained** [comment]
added (04d9f77bfa4551c0363b0988bca37e6c3e26410a)

a bit on where I found info about sending arrow keys and other to the pseudo terminal:
https://en.wikipedia.org/wiki/ANSI_escape_code - a bit of general info
autoexpect - program to record interactions with a terminal (result is not 100%)
https://github.com/saitoha/trachet/blob/master/trachet/seqdb.py - a list of keys and their byte representations (or something like that)

**Comment by Alexey-T** [comment]
Thanks
