### ISSUE TITLE
'git diff' blocks entering of more commands, stucks

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_terminal_plus#50]
[Screencast 2021-02-25 13:27:18.zip](https://github.com/halfbrained/cuda_terminal_plus/files/6042260/Screencast.2021-02-25.13.27.18.zip)

**Comment by Alexey-T** [comment]
@halfbrained is it a bug?

**Comment by halfbrained** [comment]
to exit `less` enter `q`
