### ISSUE TITLE
MColor class: 2 words 'MColor.' are needed here?

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_terminal_plus#52]
![Screenshot from 2021-02-25 13-35-28](https://user-images.githubusercontent.com/4154978/109141098-65070980-776e-11eb-89ed-a9ff70dd3b94.png)

**Comment by halfbrained** [comment]
Well yes, those are static methods. Is there something wrong with them?

**Comment by Alexey-T** [comment]
yes, Ok.
