### ISSUE TITLE
memo painting is bad with 'less filename" and Down arrow

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_terminal_plus#54]
`less snippets.json`

file https://github.com/Alexey-T/CudaText-registry/blob/master/json/snippets.json

I press down-key n times and get bad text
![Screenshot from 2021-02-25 21-19-10](https://user-images.githubusercontent.com/4154978/109198482-53922180-77af-11eb-8704-e44c70837966.png)

**Comment by halfbrained** [comment]
~~`less` just adds scrolling for text. For `git diff` command - git is the one adding colors. So this is normal, same will happen in other terminals.~~

Sorry, got your meaning now... looking

**Comment by halfbrained** [comment]
increased pseudo-terminal width, we are using Editor's wrapping anyway. Should work well in most cases.

Will look tomorrow if there is a better way

**Comment by Alexey-T** [comment]
now it's Ok.

**Comment by Alexey-T** [comment]
(close if fixing is done).
