### ISSUE TITLE
disable URL highlighte for memo

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_terminal_plus#55]
![Screenshot from 2021-02-25 22-11-47](https://user-images.githubusercontent.com/4154978/109204591-973c5980-77b6-11eb-8afc-05904da757e7.png)

PROP_LINK_AT_POS: str: URL in the document, at given position. Value must be str(pos_x)+","+str(pos_y).
PROP_LINKS_SHOW: bool: enable hyperlinks underlining.
PROP_LINKS_REGEX: str: regular expression for hyperlinks.
PROP_LINKS_CLICKS: int: how mouse clicks activate hyperlinks. 0: disabled, 1: single click, 2: double click.

**Comment by halfbrained** [comment]
fixed
