### ISSUE TITLE
plugin don't work on macOS (10.11-10.12)

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_terminal_plus#56]
I guess you cannot test it. this needs the macOS distro or real mac. I have some real mac. on running the terminal, black memo shows this text-`.....smth.... cannot use this CoreFoundaition api..... you must use exec().....`.
Console panel don't show error.

if you cannot check it on mac, I understand.

**Comment by halfbrained** [comment]
I have a VM with macOS 10.15.7, will check it out.

**Comment by halfbrained** [comment]
fixed
(macos is... something)

**Comment by Alexey-T** [comment]
thanks!
