### ISSUE TITLE
Is it possible to color the terminal from Cud theme?

### ISSUE THREAD

**Issue by eltonfabricio10** [halfbrained/cuda_terminal_plus#59]
Also set the local language to not display this message:

`bash: warning: setlocale: LC_ALL: cannot change locale (en_GB.UTF-8)`

**Comment by Alexey-T** [comment]
But Cud theme don't provide such colors (for terminal)!

**Comment by Alexey-T** [comment]
About 'bash error line': did you install some i18n package for Cud? I don't see that msg of course.

**Comment by eltonfabricio10** [comment]
> About 'bash error line': did you install some i18n package for Cud? I don't see that msg of course.

Nope! i18n default

**Comment by eltonfabricio10** [comment]
> But Cud theme don't provide such colors (for terminal)!

Can't get "ui color" by API?

**Comment by Alexey-T** [comment]
API allows to get colors, but no such item in themes at all.

**Comment by eltonfabricio10** [comment]
For example, terminal background color equals editor background color

**Comment by halfbrained** [comment]
Last items in the foreground/background terminal theme colors are defaults, maybe allow to put a dash `-` there to use editor's background/font colors?

**Comment by eltonfabricio10** [comment]
yes it can be my friend

**Comment by Alexey-T** [comment]
Yes, dash value will be ok.

**Comment by halfbrained** [comment]
@eltonfabricio10 thanks for the suggestion, it was a bit annoying to do, but I'm happy with how it looks

**Comment by Alexey-T** [comment]
Look OK
![Screenshot from 2021-07-31 19-19-59](https://user-images.githubusercontent.com/4154978/127746070-a328bbe4-e44f-4f91-b3ef-b9e3f090b9c6.png)

**Comment by eltonfabricio10** [comment]
> @eltonfabricio10 thanks for the suggestion, it was a bit annoying to do, but I'm happy with how it looks

Very good my friend!
