### ISSUE TITLE
'neofetch' command results look like this, easy to fix?

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_terminal_plus#61]
![Screenshot from 2021-07-31 19-22-05](https://user-images.githubusercontent.com/4154978/127746132-db7f69bb-0fa6-44a9-9da8-991c1070d630.png)

**Comment by halfbrained** [comment]
unable to pinpiont the issue, will come back to it tomorrow

**Comment by halfbrained** [comment]
Not an easy fix. It prints better if I change `pyte` terminal size, but I need it as is for text wrapping (if memory serves), so I can't fix this.

**Comment by Alexey-T** [comment]
Okay
