### ISSUE TITLE
feature: Up/Down keys to select a command

### ISSUE THREAD

**Issue by eltonfabricio10** [halfbrained/cuda_terminal_plus#62]

**Comment by halfbrained** [comment]
Up and Down are used to scroll terminal text, also Down is used to scroll interactive scrollers like `less`, so I can't use these keys

**Comment by eltonfabricio10** [comment]
And PageUp/PageDown keys? 
Or left/right keys?

**Comment by halfbrained** [comment]
Those are in use. Alt+Up/Down maybe?

And to clarify - you mean: cycle through history like Up/Down do in Console?

**Comment by eltonfabricio10** [comment]
Yes, sorry for not saying my idea correctly

**Comment by eltonfabricio10** [comment]
![Captura de tela de 2021-08-01 13-01-42](https://user-images.githubusercontent.com/25956396/127779951-e5b2f818-da71-4a25-987d-6048eb492925.png)

Can't put this message on the statusbar instead on this panel?

**Comment by halfbrained** [comment]
Added 'Alt+Up/Down'

> Can't put this message on the statusbar instead on this panel?

There needs to be a panel for a sidebar button - so I can't

**Comment by eltonfabricio10** [comment]
> Added 'Alt+Up/Down'

Thanks my friend

> There needs to be a panel for a sidebar button - so I can't

Can't hide the panel when opening the floating window?

**Comment by halfbrained** [comment]
> Can't hide the panel when opening the floating window?

I probably can, but I don't really care enough to do that, sorry

**Comment by eltonfabricio10** [comment]
Anyway, thanks my friend!
