### ISSUE TITLE
fix for command names in install.inf

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_terminal_plus#8]
1.
Curren File-Terminal switch
->
Toggle focus: editor - it's terminal

2.
Next
->
Focus next Terminal

Previous
->
Focus previous Terminal

3.
Execute in terminal
->
Execute selected text in Terminal

**Comment by halfbrained** [comment]
This looks good?
![termmenu](https://user-images.githubusercontent.com/74829192/107772640-26705880-6d45-11eb-91b1-159ca1d814d9.png)

**Comment by halfbrained** [comment]
This looks good?
![termmenu](https://user-images.githubusercontent.com/74829192/107772984-a5fe2780-6d45-11eb-8664-1c2bbe7c403b.png)

**Comment by Alexey-T** [comment]
'Execute selected text in Terminal'
и еще хочется Such text case in sentence.
и еще хочется отделить 3 команды Close

**Comment by Alexey-T** [comment]
'Add Terminal for OS home dir' нету

**Comment by halfbrained** [comment]
> 'Add Terminal for OS home dir' нету

"Add Terminal" - is it

**Comment by Alexey-T** [comment]
better long name of command IMO.

**Comment by halfbrained** [comment]
Sure. I'm just often inconvenienced by cluttered menus :)

**Comment by Alexey-T** [comment]
but long names are clear to users... what they do.
