### ISSUE TITLE
History implementation

### ISSUE THREAD

**Issue by halfbrained** [halfbrained/cuda_terminal_plus#9]
My suggestion:
* Large global history. Accessed via a Command, shows `Editor.complete()` dialog, filtered by current string in the input (somewhat like Ctrl+R in `bash`)
* Plus short history per terminal. Shows in `editor_combo` menu as it did previously...
    * or no local history, and just show n last commands from global history here.

@Alexey-T

**Comment by Alexey-T** [comment]
I am not sure why 'short local history' is needed, maybe we can have option "local_history" for count of items in 'local history'? if 0, its disabled?

**Comment by Alexey-T** [comment]
and option global_history=50 would be good too.

**Comment by halfbrained** [comment]
Well terminals not necessarily will all be related, so some separation will be helpful in that case.
Ok, when `local_history` is zero, last commands will be pulled from global history.

> and option global_history=50 would be good too.

Sure
